# Generated by Django 6.0.3 on 2026-03-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_personalizedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='personalized_articles', to='news.tag'),
        ),
    ]
