# Generated by Django 6.0.3 on 2026-03-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articleaudio_dailypodcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleaudio',
            name='alignment_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
