# Generated by Django 6.0.3 on 2026-03-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articleaudio_alignment_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
